### ISSUE TITLE
Double percent symbol comment highlights next line as comment

### ISSUE THREAD

**Issue by rlivings39** [gauravsavadi/MATLAB-Language-grammar#2]
Comment lines containing just `%%` followed by a space cause the next line to also show as a comment:
```matlab
%% 
y = y + 1;
y = y + 1;
```
Originally reported in Gimly/vscode-matlab#58

**Comment by zhaouv** [comment]
It was fixed in pr #65.  
Gimly merged the pr. But it had not been pushed to the Market.  
You can fix it yourself by changing this file  
`%USERPROFILE%/.vscode/extensions/Gimly81.matlab-0.9.0/syntaxes/matlab.tmLanguage`  
https://github.com/Gimly/vscode-matlab/pull/65/files

**Comment by rlivings39** [comment]
Nice! Thanks for the info @zhaouv. Hopefully we can integrate that here.

**Comment by gauravsavadi** [comment]
This has been fixed in the MathWorks grammar through https://github.com/mathworks/MATLAB-Language-grammar/commit/a9f4e0d7de638793494c22f381067e1e6247a186
