### ISSUE TITLE
Functions are not highlighted properly

### ISSUE THREAD

**Issue by Gimly** [gauravsavadi/MATLAB-Language-grammar#3]
I recently accepted a PR from @rlivings39 that added this syntax grammar as part of the Matlab Visual Studio Code extension. Even though it did fix a few issues, it also brought some new issues. For example, there was highlighting for functions on the grammar I was using before and it seems to have disappeared with the new syntax.

Could you please add this in your syntax?

see https://github.com/Gimly/vscode-matlab/issues/76
https://github.com/Gimly/vscode-matlab/issues/38

**Comment by gauravsavadi** [comment]
Hello @Gimly,

**Comment by gauravsavadi** [comment]
@Gimly 

We do not currently plan to add highlighting to functions. Here is the rationale: github/linguist#3904 (comment).

The workaround mentioned in https://github.com/Gimly/vscode-matlab/issues/76 should work for VSCode.

**Comment by Gimly** [comment]
OK, closing the issue since this was fixed by adding another grammar. Thanks for the help.
